CREATE TABLE FILE (ID BIGINT NOT NULL, TYPE VARCHAR(31), DESCRIPTION VARCHAR(255), NAME VARCHAR(255), URI BYTEA, USER_ID BIGINT, DTYPE VARCHAR(31), PRIMARY KEY (ID));
CREATE TABLE IMAGE (ID BIGINT NOT NULL, THUMBNAILURI BYTEA, PRIMARY KEY (ID));
CREATE TABLE "user" (ID BIGINT NOT NULL, EMAIL VARCHAR(255), PASSWORD VARCHAR(255), ROLE VARCHAR(255), PRIMARY KEY (ID));
ALTER TABLE IMAGE ADD CONSTRAINT FK_IMAGE_ID FOREIGN KEY (ID) REFERENCES FILE (ID);
CREATE SEQUENCE USER_ID_SEQ INCREMENT BY 50 START WITH 50;
CREATE SEQUENCE FILE_ID_SEQ INCREMENT BY 50 START WITH 50;
